version: "3"
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/app/node_modules
      - /c/Users/newst/Desktop/dockerfile-folder/docker-react-app:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      # - FAST_REFRESH=false
      # - NODE_ENV=development

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - /c/Users/newst/Desktop/dockerfile-folder/docker-react-app:/usr/src/app
    command: ["npm", "run", "test"]
